{% set name = "ufs2arco" %}
{% set version = "0.17.1" %}
{% set build = 0 %}

{% set nompi = nompi or 'mpi' %}
{% set install_with_mpi4py = nompi == "mpi" %}

{% if install_with_mpi4py %}
{% set mpi_prefix = "mpi" %}
# prioritize mpi via build number
{% set build = build + 100 %}
{% else %}
{% set mpi_prefix = "nompi" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ufs2arco-{{ version }}.tar.gz
  sha256: 0f7eb9ce3e5446a2d6525b6eecfcff842951533ef6960281421876f2482444fd

build:
  entry_points:
    - ufs2arco = ufs2arco.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  string: {{ mpi_prefix }}_pyh{{ PKG_HASH }}_{{ build }}
  number: {{ build }}

requirements:
  host:
    - python  {{ python_min }}
    - setuptools >=64.0.0
    - setuptools-scm >=8
    - pip
  run:
    - python  >={{ python_min }}
    - numpy <2.3
    - xarray
    - cf_xarray
    - cftime
    - netcdf4
    - h5netcdf
    - zarr <3
    - cfgrib
    - bottleneck
    - flox
    - dask-core
    - fsspec
    - s3fs
    - gcsfs
    - xesmf
    - esmf * nompi*
    # conda smithy complains about selectors, so use jinja
{% if install_with_mpi4py %}
    - mpi4py
{% endif %}

test:
  imports:
    - ufs2arco
  commands:
    - pip check
    - ufs2arco --help
  requires:
    - python  {{ python_min }}
    - pip

about:
  home: https://github.com/NOAA-PSL/ufs2arco
  summary: Tools for converting Unified Forecast System (UFS) output to Analysis Ready, Cloud Optimized (ARCO) format
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/NOAA-PSL/ufs2arco
  doc_url: https://ufs2arco.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - timothyas
