{% set name = "ufs2arco" %}
{% set version = "0.15.1" %}
{% set python_min = "3.10" %}

outputs:
  - name: {{ name }}
    build:
      entry_points:
        - ufs2arco = ufs2arco.cli:main
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=64.0.0
        - setuptools-scm >=8
        - pip
      run:
        - python >={{ python_min }}
        - numpy <2.3
        - xarray
        - cf_xarray
        - cftime
        - netcdf4
        - h5netcdf
        - zarr <3
        - cfgrib
        - bottleneck
        - flox
        - dask-core
        - fsspec
        - s3fs
        - gcsfs
        - esmf=*=nompi*
        - xesmf
        - mpi4py
    test:
      imports:
        - ufs2arco
      commands:
        - pip check
        - ufs2arco --help
      requires:
        - python {{ python_min }}
        - pip
    about:
      home: https://github.com/NOAA-PSL/ufs2arco
      summary: Tools for converting Unified Forecast System (UFS) output to Analysis Ready, Cloud Optimized (ARCO) format
      license: Apache-2.0
      license_file: LICENSE
      dev_url: https://github.com/NOAA-PSL/ufs2arco
      doc_url: https://ufs2arco.readthedocs.io/en/latest

  - name: {{ name }}-nompi
    build:
      entry_points:
        - ufs2arco = ufs2arco.cli:main
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
      number: 0
    requirements:
      host:
        - python {{ python_min }}
        - setuptools >=64.0.0
        - setuptools-scm >=8
        - pip
      run:
        - python >={{ python_min }}
        # No mpi4py here!
        - numpy <2.3
        - xarray
        - cf_xarray
        - cftime
        - netcdf4
        - h5netcdf
        - zarr <3
        - cfgrib
        - bottleneck
        - flox
        - dask-core
        - fsspec
        - s3fs
        - gcsfs
        - esmf=*=nompi*
        - xesmf
    test:
      imports:
        - ufs2arco
      commands:
        - pip check
        - ufs2arco --help
      requires:
        - python {{ python_min }}
        - pip
    about:
      home: https://github.com/NOAA-PSL/ufs2arco
      summary: Tools for converting Unified Forecast System (UFS) output to Analysis Ready, Cloud Optimized (ARCO) format (no MPI support)
      license: Apache-2.0
      license_file: LICENSE
      dev_url: https://github.com/NOAA-PSL/ufs2arco
      doc_url: https://ufs2arco.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - timothyas
